name: Unity WebGL Build

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Unity
      uses: webbertakken/unity-actions@v2
      with:
        unityVersion: '2021.3.20f1'
    - name: Build WebGL
      run: |
        /opt/Unity/Editor/Unity \
        -quit \
        -batchmode \
        -executeMethod WebGLBuilder.Build \
        -projectPath ${{ github.workspace }}
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.12.0
      with:
        branch: gh-pages
        folder: Build
